- name: Install Apache
  apt: name="apache2" state=present

- name: Install mod PHP for Apache
  apt: name=libapache2-mod-php state=present

- name: Install libsass
  apt: name="{{ item }}"
  with_items:
    - libsass0
    - libsass-dev
