---

- name: Install PHP (Ubuntu 14.04)
  apt: name="{{ item }}" state=present
  with_items:
    - php5
    - php-apc
    - php5-bcmath
    - php5-cgi
    - php5-curl
    - php5-gd
    - php5-imagick
    - php5-json
    - php5-mbstring
    - php5-mcrypt
    - php5-mysqlnd
    - php5-sqlite
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Install PHP (Ubuntu 16.04)
  apt: name="{{ item }}" state=present
  with_items:
    - php
    - php-apcu
    - php-bcmath
    - php-cgi
    - php-curl
    - php-gd
    - php-imagick
    - php-json
    - php-mbstring
    - php-mcrypt
    - php-mysqlnd
    - php-sqlite3
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: Install Composer
  apt: name=composer state=latest

- name: Enable PHP mods
  shell: "phpenmod {{ item }}"
  with_items:
    - bcmath
    - curl
    - dom
    - mbstring
    - mcrypt
    - phar
    - xml
